name: node-run

on:
  workflow_dispatch:
    inputs:
      data:
        description: text
        required: true
        type: string

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - run: node index.js
        env:
          INPUT: ${{ inputs.data }}
